###

POST http://localhost:3000/campaigns

{
    "name": "nova campanha 1333",
    "content": "nova campanha de teste para empresa X",
    "emails": ["teste@teste.com.br", "testefulano@email.com"]
}

###

GET http://localhost:3000/campaigns